<div style="font-size: 0.8em; ">
<p class="text-primary"><span style="text-align: center; ">By signing up for membership or continuing with us, you agree to the following Terms, Conditions and Disclaimers :Participants should therefore note that there is a considerable risk involved in any system. FundsForLife or its participants will not be liable for any loss resulting from downturn in the system. Participants that are not comfortable with this risk can simply disagree and not be members of FundsForLife.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">This service is provided on an as is, as available service. We make no warranties of any kind, either expressed or implied.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">We reserve the right to add or remove features and functionality, make changes on how the platform works, manage memberships, within this site, and otherwise make changes to the service and this agreement without notice.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">We may terminate without notice, at our sole discretion, any membership deemed to be in breach of this agreement or otherwise found to be abusing or misusing the service, or harassing the other members or administrator in any way.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">In the unlikely event that this program should ever terminate it's operations, it's creator, operators, employees, assigns and successors shall not be held liable for any loss whatsoever to our members.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">We make no claims on how much money you can get with our program. Your ability to earn depends on a number of factors, including where and how (and how often) we get new members, and the motivation and time it takes our system to pair your donor to you. Individual results will vary.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">Members caught spamming or otherwise causing harm to our program will have their accounts terminated, and maybe prosecuted for their actions. We will investigate all allegations before taking action.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">All donations are final. No refunds. </span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">FundsForLife shall not be held responsible for any delay in pairing or be blamed for the time any member is paired as pairing must be accepted at any pace the system pair donors to members.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">FundsForLife shall not be blamed or held responsible for any delay or refusal in payment of any paired donor of our members. Only guiders have the right to refuse payment of any fake proof of payment uploaded by any participants.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">We shall not be held responsible for any donation lost in any way even through deactivation of an account.</span></p><br><br>
<p class="text-primary"><span style="text-align: center; ">By creating an account with us, you agree all terms and conditions.</span></p><br><br>
</div>